name: publish

on:
  workflow_dispatch:

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Test Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u richard-fowles-ntt --password-stdin
        docker build --file ./sample-packages/docker/Dockerfile -t ghcr.io/richard-fowles-ntt/test_publish:latest .
        docker push ghcr.io/Richard-Fowles-NTT/test_publish:latest
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
